version: 0.2
phases:
  pre_build:
    on-failure: CONTINUE
    commands:
      - npm install -g @aws-amplify/cli
      - aws configure set aws_access_key_id AKIAXVPPYZEKBYBLZBJC 
      - aws configure set aws_secret_access_key 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 
      - aws configure set default.region eu-central-1
      - aws amplify create-branch --app-id=dcy9ioq1oqxov --branch-name=$BranchName --environment-variables EC2=$EC2_URL,REDIRECT=https://$BranchName.dcy9ioq1oqxov.amplifyapp.com,ID=$BranchName.dcy9ioq1oqxov.amplifyapp.com
   post_build:
    commands:
      - aws amplify update-branch --app-id=dcy9ioq1oqxov --branch-name=$BranchName --environment-variables EC2=$EC2_URL,REDIRECT=https://$BranchName.dcy9ioq1oqxov.amplifyapp.com,ID=$BranchName.dcy9ioq1oqxov.amplifyapp.com
      
