version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - git remote add origin https://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@github.com/PKolodziejsky/myapp
      - cd teams-app
      - npm ci

      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm run build:dev
  build:
    commands:
      - aws s3 sync build/ $WEBSITE_S3_BUCKET/