version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd teams-app
      - npm install

      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm run build
  build:
    commands:
      - aws s3 sync build/ $WEBSITE_S3_BUCKET/