version: 0.2
phases:
  pre_build:
    on-failure: CONTINUE
    commands:
      - npm install -g @aws-amplify/cli
      - wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
      - chmod +x ./jq
      - cp jq /usr/bin
      - export AWS_PROFILE=default
      - aws configure set default.region eu-central-1
      - aws ec2 reboot-instances --instance-ids $EC2_ID
      - aws amplify create-branch --app-id=dcy9ioq1oqxov --branch-name=$BranchName --environment-variables EC2=$EC2_URL,REDIRECT=https://$BranchName.dcy9ioq1oqxov.amplifyapp.com,ID=$BranchName.dcy9ioq1oqxov.amplifyapp.com
      - curl -X POST $(aws amplify create-webhook --app-id dcy9ioq1oqxov --branch-name $BranchName | jq -r '.webhook.webhookUrl')
  post_build:
    commands:
      - aws amplify update-branch --app-id=dcy9ioq1oqxov --branch-name=$BranchName --environment-variables EC2=$EC2_URL,REDIRECT=https://$BranchName.dcy9ioq1oqxov.amplifyapp.com,ID=$BranchName.dcy9ioq1oqxov.amplifyapp.com
