version: '3.1'

services:
  mongodb:
    container_name: seatti_api_mongo_db
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongoCreateUser.js:/docker-entrypoint-initdb.d/mongoCreateUser.js:ro
      - mongodb:/data/db
  seatti-api:
    image: 527173208340.dkr.ecr.eu-central-1.amazonaws.com/seatti-app-staging
    pull_policy: build
    ports:
      - 443:3030
      - 80:3030
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      ADDRESS: "localhost"
      PORT: 3030
      MONGO_DB_HOST: "host.docker.internal"
      MONGO_DB_PORT: 27017
      MONGO_DB_NAME: "admin"
      MONGO_DB_USER: "root"
      MONGO_DB_PASSWORD: "SECRET_PLACEHOLDER"
      MONGO_DB_CONNECTION: "mongodb"
      GRAPHQL_PLAYGROUND: "false"
      GRAPHQL_DEBUG: "false"
      APP_ID: "0a3b1bb1-b4b2-4bdf-8eea-c41ee08c5dc3"
      APP_SECRET: "oHn7Q~YtEPAPfbLyghcuws_X_MvrYyQ2i5gnz"
      AWS_PROFILE: "seatti"
      AWS_S3_MEDIA_BUCKET: "seatti-media-dev"
    depends_on:
      mongodb:
        condition: service_started
    command: npx ts-node src/seeds

volumes:
  mongodb:
  mongoCreateUser.js:
    