
name: CodeCommit

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        env:
          AWS_DEFAULT_REGION: eu-central-1
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_PIOTR }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_PIOTR }}
        shell: bash
        run: |
          git remote add codecommit https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/myapp
          git push codecommit main --force

